config/routes.rb
Rails.application.routes.draw do
  get "payments/create"
  get "/dashboard", to: "dashboard#show"
  get "/auth/auth0/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"
  get "/auth/logout" => "auth0#logout"
  get "/auth/redirect", to: redirect("/auth/auth0")
  post "payments", to: "payments#create"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "clothings/search", to: "clothings#search", as: :search_clothings
  get "clothings/autocomplete", to: "clothings#autocomplete"
  resources :clothings, only: [ :index, :new, :create, :show, :edit, :update, :destroy ] do
    resources :reviews, only: [ :create, :destroy ]
    collection do
      get "admin_page", to: "clothings#admin_page"
    end
  end
  resource :cart, only: [ :show ] do
    post "add/:clothings_id", to: "carts#add", as: :add_clothings
    delete "remove/:clothings_id", to: "carts#destroy", as: :remove_clothings
  end

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "clothings#index"
end

app/models/clothing.rb
class Clothing < ApplicationRecord
  has_one_attached :image
  has_many :reviews, dependent: :destroy
  validates :classification, presence: true
  validates :brand, presence: true
  validates :name, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates :material, presence: true
  validates :size, presence: true
  validates :for_whom, presence: true
end

app/models/clothings.rb
class Clothings < ApplicationRecord
 validates :classification, presence: true
 validates :brand, presence: true
 validates :name, presence: true
 validates :price, numericality: { greater_than_or_equal_to: 0 }
 validates :material, presence: true
 validates :size, presence: true
 validates :for_whom, presence: true
end

app/controllers/clothings_controller.rb
class ClothingsController < ApplicationController
  include Secured

  before_action :require_admin!, only: [ :destroy, :edit, :update, :create, :new ]

  def index
    @sort_field = %w[price name].include?(params[:sort_by]) ? params[:sort_by] : "price"
    @sort_order = params[:sort] == "desc" ? "desc" : "asc"
    @clothings = Clothing.all

    if params[:for_whom].present?
      @clothings = @clothings.where(for_whom: params[:for_whom])
    end
    if params[:category].present?
      @clothings = @clothings.where(classification: params[:category])
    end

    @clothings = @clothings.order(@sort_field => @sort_order)
  end

  def show
    @clothing = Clothing.find(params[:id])
    @average_rating = @clothing.reviews.average(:rating)&.round(1) || 0
  end

  def search
    if params[:q].present?
      query = "%#{params[:q]}%"
      @clothings = Clothing.where("name LIKE ? OR brand LIKE ? OR material LIKE ?", query, query, query)
    else
      @clothings = []
    end
  end
  def autocomplete
    query = params[:q].to_s.strip
    results = Clothing.where("name LIKE ? OR brand LIKE ?", "%#{query}%", "%#{query}%").limit(5)

    render json: results.select(:id, :name, :brand)
  end

  def create
    @clothing = Clothing.new(clothing_params)
    if @clothing.save
      redirect_to @clothing
    else
      render :new, status: :unprocessable_entity
    end
  end

  def admin_page
    @clothings = Clothing.all
  end

  def new
    @clothing = Clothing.new
  end

  def destroy
    @clothing = Clothing.find(params[:id])
    @clothing.destroy

    redirect_to admin_page_clothings_path
  end

  def edit
    @clothing = Clothing.find(params[:id])
  end

  def update
    @clothing = Clothing.find(params[:id])
    if @clothing.update(clothing_params)
      redirect_to @clothing
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def clothing_params
    params.require(:clothing).permit(
      :classification, :brand, :name, :price, :material, :size,
      :description, :for_whom, :image
    )
  end
end

app/views/clothings/admin_page.html.erb
 <%if session[:userinfo]&.dig('roles')&.include?('admin')%>
 
<div class="">
<% @clothings.each do |clothing| %>
  <%= link_to clothing_path(clothing.id) do %>
      <div class="clothing_conteiner_for_order">
      <%= image_tag clothing.image,class: "image_of_order" %>

       <div class="clothing-name">
       <p> <%= clothing.name %> <%= clothing.price%>$
        <%= form_with model: clothing, method: :delete, local: true do %>
       <%= submit_tag "Delite", class: "btn" %>
       <%end%>
       <%= link_to "Redact", edit_clothing_path(clothing), class: "btn" %></p>
       </div>
    </div>
    <% end %>
  <% end %>
</div>
<%end%> 

app/views/clothings/edit.html.erb
<h1>Redact clothings</h1>

<%= form_with model: @clothing, local: true do |form| %>
  <%= form.label :classification %>
  <%= form.select :classification, ['headwear', 'shoes', 't-shirts', 'jackets', 'sweaters', 'business_suits'] %><br>

  <%= form.label :brand %>
  <%= form.text_field :brand %><br>

  <%= form.label :name %>
  <%= form.text_field :name %><br>

  <%= form.label :price %>
  <%= form.number_field :price %><br>

  <%= form.label :material %>
  <%= form.text_field :material %><br>

  <%= form.label :size %>
  <%= form.text_field :size %><br>

  <%= form.label :for_whom %>
  <%= form.select :for_whom, ['for_men', 'for_women', 'unisex'] %><br>

  <%= form.label :description %>
  <%= form.text_area :description %><br>

  <%= form.label :image %>
  <%= form.file_field :image %><br>

  <%= form.submit "Save" %>
<% end %>

app/views/clothings/index.html.erb
<% unless params[:category].present?%>
<div>
  <%= link_to clothings_path(category: "t_shirts"), class: "background_category", style: "background-image: url(#{asset_path('t-shirts.jpg')}); position: relative;" do %>
    <span class="container_category">T-shirts</span>
  <% end %>
</div>
<div>
  <%= link_to clothings_path(category: "headwear"), class: "background_category", style: "background-image: url(#{asset_path('headwear.jpg')}); position: relative;" do %>
    <span class="container_category">Headwear</span>
  <% end %>
</div>
<div>
  <%= link_to clothings_path(category: "shoes"), class: "background_category", style: "background-image: url(#{asset_path('shoes.jpg')}); position: relative;" do %>
    <span class="container_category">Shoes</span>
  <% end %>
</div>
<div>
  <%= link_to clothings_path(category: "jackets"), class: "background_category", style: "background-image: url(#{asset_path('jackets.jpg')}); position: relative;" do %>
    <span class="container_category">Jackets</span>
  <% end %>
</div>
<div>
  <%= link_to clothings_path(category: "sweaters"), class: "background_category", style: "background-image: url(#{asset_path('sweaters.jpg')}); position: relative;" do %>
    <span class="container_category">Sweaters</span>
  <% end %>
</div>
<div>
  <%= link_to clothings_path(category: "business_suits"), class: "background_category", style: "background-image: url(#{asset_path('business_suits.jpg')}); position: relative;" do %>
    <span class="container_category">Business Suits</span>
  <% end %>
<%end%>

<% if params[:category].present? %>

<div class="clothing-container">
<% @clothings.each do |jackets| %>
  <%= link_to clothing_path(jackets.id) do %>
    <div class="clothing-item">
      <div class="responsive-container">
         <% if jackets.image.attached? %>
      <%= image_tag jackets.image,class: "responsive-image" %>
      <% end %>
       <div class="clothing-name">
        <%= jackets.name %>
       </div>
       <div class="clothing-prise">
        <%= jackets.price%>$
        </div>
      </div>
    </div>
    <% end %>
  <% end %>
</div>
<%end%>

app/views/clothings/new.html.erb
<h1>Add Clothings</h1>

<%= form_with model: @clothing, local: true do |form| %>
  <%= form.label :classification %>
  <%= form.select :classification, ['headwear', 'shoes', 't-shirts', 'jackets', 'sweaters', 'business_suits'] %><br>

  <%= form.label :brand %>
  <%= form.text_field :brand %><br>

  <%= form.label :name %>
  <%= form.text_field :name %><br>

  <%= form.label :price %>
  <%= form.number_field :price %><br>

  <%= form.label :material %>
  <%= form.text_field :material %><br>

  <%= form.label :size %>
  <%= form.text_field :size %><br>

  <%= form.label :for_whom %>
  <%= form.select :for_whom, ['for_men', 'for_women', 'unisex'] %><br>

  <%= form.label :description %>
  <%= form.text_area :description %><br>

 <%= form.label :image, "Add images" %><br>
  <%= form.file_field :image %><br>
  
  <%= form.submit "Add" %>
<% end %>

<% if @clothing.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@clothing.errors.count, "error") %> prohibited this clothing from being saved:</h2>
    <ul>
      <% @clothing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/clothings/search.html.erb
<h1>Results</h1>

<% if @clothings.any? %>
  <% @clothings.each do |clothing| %>
    <div>
      <%= link_to clothing.name, clothing_path(clothing) %>
      <p><%= clothing.brand %> — <%= clothing.material %></p>
    </div>
  <% end %>
<% else %>
  <p>Nothing</p>
<% end %>

app/views/clothings/show.html.erb
<%= javascript_importmap_tags "delete_confirm" %>
<%= javascript_importmap_tags "delete_reviews" %>
<%= javascript_include_tag "review_replies", defer: true %>

<div>
<%= button_to add_clothings_cart_path(@clothing.id), class:"btn"  do%>
 Add to cart
 <% end %>
 <p>
<% if session[:userinfo]&.dig('roles')&.include?('admin') %>
 <%= form_with model: @clothing, method: :delete, local: true, html: { id: "delete-clothing-form" } do %>
  <%= submit_tag "Delete", class: "btn" %> <%= link_to "Redact", edit_clothing_path(@clothing), class: "btn" %>
<% end %>
<p>
<% end %>

<% if @clothing.image.attached? %>
   <%= image_tag @clothing.image,class: "responsive-image" %>
<% end %>

<div class="clothing-name">
<%= @clothing.name %>
<div class="star-rating">
  <div class="stars-outer">
    <div class="stars-inner" style="width: <%= (@average_rating.to_f / 5 * 100).round %>%"></div>
  </div>
  <span>(<%= @average_rating %>/5)</span>
</div>
</div>

<div>
brand: <%= @clothing.brand %>
</div>
<div>
size: <%= @clothing.size %>
</div>
<div>
prise: <%= @clothing.price %>$
</div>
<div>
material_type: <%= @clothing.material %>
</div>
<div>
description: <%= @clothing.description %>
</div>
</div>



<h2>Reviews</h2>

<% if session[:userinfo] %>
  <%= form_with(url: clothing_reviews_path(@clothing), model: Review.new, local: true) do |form| %>
    <div>
      <%= form.label :content, "Review" %><br>
      <%= form.text_area :content %>
    </div>

    <div>
      <%= form.label :rating, "Stars" %><br>
      <%= form.select :rating, options_for_select(1..5), prompt: "Stars" %>
      <%= form.submit "Add review" %>
    </div>
  <% end %>
<% else %>
  <p>Only logged in users can comment. <%= link_to "Login", "/auth/auth0" %></p>
<% end %>

<%# Отображаем ТОЛЬКО корневые отзывы через partial с рекурсией %>
<% @clothing.reviews.where(parent_id: nil).each do |review| %>
  <%= render partial: "reviews/review", locals: { review: review, depth: 0 } %>
<% end %>

<% if session[:userinfo] %>
<div id="reply-form" style="display: none;">
  <%= form_with model: [@clothing, Review.new], local: true do |form| %>
    <%= form.hidden_field :parent_id %>
    <%= form.label :content, "Ваш ответ" %><br>
    <%= form.text_area :content %>
    <%= form.submit "Ответить" %>
  <% end %>
</div>
<% else %>
  <p>Only logged in users can reply to reviews. <%= link_to "Login", "/auth/auth0" %></p>
<%end%>