config/routes.rb
Rails.application.routes.draw do
  get "payments/create"
  get "/dashboard", to: "dashboard#show"
  get "/auth/auth0/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"
  get "/auth/logout" => "auth0#logout"
  get "/auth/redirect", to: redirect("/auth/auth0")
  post "payments", to: "payments#create"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "clothings/search", to: "clothings#search", as: :search_clothings
  get "clothings/autocomplete", to: "clothings#autocomplete"
  resources :clothings, only: [ :index, :new, :create, :show, :edit, :update, :destroy ] do
    resources :reviews, only: [ :create, :destroy ]
    collection do
      get "admin_page", to: "clothings#admin_page"
    end
  end
  resource :cart, only: [ :show ] do
    post "add/:clothings_id", to: "carts#add", as: :add_clothings
    delete "remove/:clothings_id", to: "carts#destroy", as: :remove_clothings
  end

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "clothings#index"
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  include Secured
  before_action :require_login!, only:  [ :create ]
  before_action :require_admin!, only: [ :destroy ]

        def create
          @clothing = Clothing.find(params[:clothing_id])
          @review = @clothing.reviews.new(review_params)
          @review.user_name = session[:userinfo]["info"]["name"]

          if @review.save
            redirect_to @clothing, notice: "Спасибо за отзыв!"
          else
            redirect_to @clothing, alert: "Пожалуйста, заполните все поля."
          end
        end
        def destroy
          @clothing = Clothing.find(params[:clothing_id])
          @review = @clothing.reviews.find(params[:id])
          @review.destroy
          redirect_to @clothing
        end

        private

        def review_params
          params.require(:review).permit(:content, :rating, :parent_id)
        end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_review.html.erb
<div class="review_container" style="margin-left: <%= depth * 20 %>px;">
<div>
  <strong><%= review.user_name %></strong>
  <%= review.created_at.strftime("%d-%m-%Y") %>
  <div class="star-rating">
    <div class="stars-outer">
      <div class="stars-inner" style="width: <%= (review.rating.to_f / 5 * 100).round %>%"></div>
    </div>
  </div>

    <% if session[:userinfo] %>
    <%= link_to "Answer", "#", data: { reply_to: review.id }, class: "reply-link" %>
    <% end %>
  </div>
  <div class= "revew_content">
  <%= review.content %>
  </div>

  <% if session[:userinfo]&.dig('roles')&.include?('admin') %>
  <%= form_tag clothing_review_path(@clothing, review), method: :delete, local: true, class: "delete-review-form" do %>
    <%= submit_tag "Delite", class: "btn" %>
  <% end %>
  <% end %>

  <% review.replies.each do |reply| %>
    <%= render partial: "reviews/review", locals: { review: reply, depth: depth + 1 } %>
  <% end %>
</div>