config/routes.rb
Rails.application.routes.draw do
  get "payments/create"
  get "/dashboard", to: "dashboard#show"
  get "/auth/auth0/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"
  get "/auth/logout" => "auth0#logout"
  get "/auth/redirect", to: redirect("/auth/auth0")
  post "payments", to: "payments#create"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "clothings/search", to: "clothings#search", as: :search_clothings
  get "clothings/autocomplete", to: "clothings#autocomplete"
  resources :clothings, only: [ :index, :new, :create, :show, :edit, :update, :destroy ] do
    resources :reviews, only: [ :create, :destroy ]
    collection do
      get "admin_page", to: "clothings#admin_page"
    end
  end
  resource :cart, only: [ :show ] do
    post "add/:clothings_id", to: "carts#add", as: :add_clothings
    delete "remove/:clothings_id", to: "carts#destroy", as: :remove_clothings
  end

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "clothings#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Elle Marko" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link href="https://fonts.googleapis.com/css2?family=Parisienne&display=swap" rel="stylesheet">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_importmap_tags "search_autocomplete" %>
  </head>

  <body class= "background" style="background-image: url('<%= asset_path "background.jpg" %>');">
    <header class="site-header">
   <div>
     <div class="title_wrapper">
     <%= link_to "Elle Marko", clothings_path, class: "title_style" %>
      </div>

     <% if session[:userinfo]&.dig('roles')&.include?('admin') %>
     <p><strong>name:</strong> <%= session[:userinfo]["info"]["name"] %></p>
     <div><%= link_to "AdminPage", admin_page_clothings_path, class: "btn" %>
     <%= link_to "New", new_clothing_path, class: "btn" %>
     <%= link_to "Dashboard", dashboard_path, class: "btn" %>
     <%= link_to "logout", "/auth/logout", class: "btn" %>
     </div>
     <%elsif session[:userinfo]%>
     <p><strong>name:</strong> <%= session[:userinfo]["info"]["name"] %></p>
     <%= link_to "Dashboard", dashboard_path, class: "btn" %>
     <%= link_to "logout", "/auth/logout", class: "btn" %>
     </div>
    <% else %>
    <p>Not autorize <%= link_to "login", "/auth/auth0", class: "btn" %></p>
    <% end %>
    </div>
    <%= link_to cart_path do %>
     <span class="cart_style"> Cart (<%= cookies.signed[:cart].values.sum %>)</span>
  <%end%>

<div id="search-container" style="position: relative;">
  <%= form_with url: search_clothings_path, method: :get, local: true do %>
    <%= label_tag :q, "Поиск:" %>
    <%= text_field_tag :q, params[:q], id: "search-input", autocomplete: "off" %>
    <%= submit_tag "Найти" %>
  <% end %>
  <div id="search-suggestions" style="position:absolute; background:white; border:1px solid #ccc; z-index:1000;"></div>
</div>

  </header>
<div class="container_for_sidebar_and_main_conteiner ">
  <div class="sidebar">
  <% if params[:category].present? && action_name == "index"%>
<div>
<div><%= link_to "First low prise", clothings_path(sort_by: "price", sort: "asc", category: params[:category], for_whom: params[:for_whom]), class: "sidebar_link_style" %></div>
<div><%= link_to "First hight prise", clothings_path(sort_by: "price", sort: "desc", category: params[:category], for_whom: params[:for_whom]), class: "sidebar_link_style" %></div>
<div><%= link_to "A-Z", clothings_path(sort_by: "name", sort: "asc", category: params[:category], for_whom: params[:for_whom]), class: "sidebar_link_style" %></div>
<div><%= link_to "Z-A", clothings_path(sort_by: "name", sort: "desc", category: params[:category], for_whom: params[:for_whom]), class: "sidebar_link_style" %></div>
<div><%= link_to "For Men", clothings_path(for_whom: "for_men", category: params[:category], sort_by: params[:sort_by], sort: params[:sort]), class: "sidebar_link_style" %></div>
<div><%= link_to "For Women", clothings_path(for_whom: "for_women", category: params[:category], sort_by: params[:sort_by], sort: params[:sort]), class: "sidebar_link_style" %></div>
<div><%= link_to "Unisex", clothings_path(for_whom: "unisex", category: params[:category], sort_by: params[:sort_by], sort: params[:sort]), class: "sidebar_link_style" %></div>
<div><%= link_to "All", clothings_path( category: params[:category], sort_by: params[:sort_by], sort: params[:sort]), class: "sidebar_link_style" %></div>
</div>
<% end %>
</div>
  <main class="main-container">
    <p><%= yield %></p>
  </main>
</div>
  <footer>
    <p>&copy; fuck you </p>
  </footer>

  </body>
</html>